//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingQualityAcademicWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInReportCard
    {
        public int Id { get; set; }
        public Nullable<int> IdStudent { get; set; }
        public Nullable<int> IdReportCard { get; set; }
        public int Scores { get; set; }
        public Nullable<int> NumberMissedLectures { get; set; }
        public Nullable<int> NumberMissedPractical { get; set; }
        public Nullable<int> NumberMissedLabs { get; set; }
    
        public virtual ReportCard ReportCard { get; set; }
        public virtual Student Student { get; set; }
    }
}
